### ISSUE TITLE
Move off of ReadMe.io

### ISSUE THREAD

**Issue by shawntabrizi** [substrate-developer-hub/docs#78]
- Must be GitHub based
- Must be Markdown based

Top candidate is Docusaurus, possibly served via GitHub pages

**Comment by JoshOrndorff** [comment]
I'm taking the lead on this, hopefully with the help of @kaichaosun.

Here's the motivation and plan for moving https://docs.google.com/document/d/1Gq0a7jFMjL1txpm21twBCLg6dcEs5SWidD3cifwfPZE/edit#

I hope to make more progress this week and will update the plan. I hope to use this issue moving forward.

**Comment by kaichaosun** [comment]
I'm working on translation and localization by following the guide:
https://docusaurus.io/docs/en/translation

**Comment by kaichaosun** [comment]
**Summary about how to do the localization:**
[doc](https://hackmd.io/@2dHpJQYgQrCqfxqXMtJTFQ/B1f6WH8A4)

**TODO:**
- [x] Enable translation and localization in Docusaurus
- [ ] Create Crowndin project with the proper account, it should be the admin of this repo, better not to use a personal account.
- [ ] Integrate with CI, blocked by Crowndin account creation.
- [ ] Discuss around version control.

**Comment by JoshOrndorff** [comment]
@kaichaosun Looks awesome. I've approved you [PR to enable l10n](https://github.com/substrate-developer-hub/docs/pull/93). FYI for the CI portions were using circleci.com. Checkout the `/circleci/config.yml`. I'll be happy to help with getting it to work with crowdin.

@shawntabrizi Let's capture our discussion from riot in here.

> You're suggesting we move this repo to substrate-developer-hub.github.io so it is our "org page". That means docusaurus would build to master, and we would do our work on source branch. We can change our github default branch to be source branch.

I'm fine with all that. Please confirm that I understood correctly.

**Comment by JoshOrndorff** [comment]
Actually, I've broken the scope of this task down into more manageable issues and put them in the "Migrate to Docusaurus" milestone.

@kaichaosun let's track the l10n progress in https://github.com/substrate-developer-hub/docs/issues/84
